### ISSUE TITLE
ddu dose not close ui when toggle of uiOptions sets v:true.

### ISSUE THREAD

**Issue by ryota2357** [Shougo/ddu.vim#24]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

If `toggle` in uiOptions is set to `v:true` and `ddu#start()` is called when the cursor is in another window, ddu closes the window at the cursor position without closing ui.

This problem occurs in both vim and neovim, ddu-ui-ff and ddu-ui-filer.

## Expected

ddu closes the ddu-ui window without closing the window at the cursor position.

## Environment Information

- ddu.vim version (SHA1): aaf11eab9078e1ece54e4c245c9f72b055d336de

- denops.vim version (SHA1): a40e0c10be0c67b5fd6cb9713914b9259dafa7e2

- deno version(`deno -V` output): deno 1.24.1

- OS: MacOS

- neovim/Vim `:version` output:

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

      システム vimrc: "$VIM/sysinit.vim"
       省略時の $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
if !has("nvim")
  set nocompatible
  filetype plugin indent on
  syntax enable
endif

let s:plugins = [
      \ 'vim-denops/denops.vim',
      \ 'Shougo/ddu.vim',
      \ 'Shougo/ddu-ui-filer',
      \ 'Shougo/ddu-source-file',
      \ ]

for item in s:plugins
  execute 'set runtimepath+=~/.cache/dein/repos/github.com/' . item
endfor

call ddu#custom#patch_global({
    \   'ui': 'filer',
    \   'sources': [{'name': 'file'}],
    \   'uiOptions': {
    \     '_': { 'toggle': v:true }
    \    },
    \ })
nnoremap <Space>o <Cmd>call ddu#start()<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start ddu by `<Space>o`
1. Move upper window by `<C-w>k`
1. `<Space>o `

## Upload the log messages by `:redir` and `:message` (if errored)

The above vimrc does not be errored. But if you use:

```vim
... snip ...
call ddu#custom#patch_global({
    \   'ui': 'filer',
    \   'sources': [{'name': 'file'}],
    \   'uiOptions': {
    \     '_': { 'toggle': v:true }
    \    },
    \   'uiParams': {
    \     '_': { 'split': 'floating' }
    \    }
    \ })
... snip ...
```

and `<Space>o` -> `<C-w>k` -> `<Space>o`, error is occured.

```
function ddu#start[1]..ddu#_request[22]..denops#request[1]..denops#server#request[6]..<SNR>30_request の処理中にエラーが検出されました:
行    1:
Error invoking 'invoke' on channel 4:
Error: Failed to call 'start' with [{}]: Error: Failed to call 'call' with ["denops#api#cmd","close!",{}]: Error: Failed to call 'nvim_call_function' with ["denops#api#cmd",["close!",{}]]: [0,"Vim(c
lose):E444: 最後のウィンドウを閉じることはできません"]
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async Service.call (file:///Users/---/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:93:12)
    at async Session.call (file:///Users/---/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:153:14)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async DenopsImpl.cmd (file:///Users/---/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops/impl.ts:51:5)
    at async Ui.quit (file:///Users/---/.cache/dein/repos/github.com/Shougo/ddu-ui-filer/denops/@ddu-uis/filer.ts:380:7)
    at async Ddu.uiQuit (file:///Users/---/.cache/dein/repos/github.com/Shougo/ddu.vim/denops/ddu/ddu.ts:448:5)
    at async Ddu.start (file:///Users/---/.cache/dein/repos/github.com/Shougo/ddu.vim/denops/ddu/ddu.ts:166:7)
    at async Session.start (file:///Users/---/.cache/dein/repos/github.com/Shougo/ddu.vim/denops/ddu/app.ts:130:7)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async Service.dispatch (file:///Users/---/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops-private/service.ts:108:14)
    at async Session.invoke (file:///Users/---/.cache/dein/repos/github.com/vim-denops/denops.vim/denops/@denops-private/host/nvim.ts:48:16)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
```

**Comment by Shougo** [comment]
Fixed.  Please update `ddu-ui-filer`.
