### ISSUE TITLE
A source plugin that uses a delayed callback deadlocks when called from ui#do_action()

### ISSUE THREAD

**Issue by Milly** [Shougo/ddu.vim#50]
# Problems summary

Implement a source plugin that waits for the result of a deferred callback via `denops#notify()` from Vim.
Calling this source from `ddu#start()` works fine, but calling it from `ui#do_action()` deadlocks and freezes the Vim UI.
Internally, it is fine when called with `denops#notify()`, and deadlocks when called with `denops#request()`.

## Expected

Do not deadlock.
We can create a source plugin that waits for a delayed callback via `denops#notify()`.

## Environment Information

- ddu.vim version (SHA1): a2c4500

- denops.vim version (SHA1): vim-denops/denops.vim@8f3899d

- deno version(`deno -V` output):
```
deno 1.32.3
```

- OS: Windows 10

- neovim/Vim `:version` output:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 23 2023 23:48:58)
MS-Windows 64-bit console version
Included patches: 1-1425
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

[The files below are also in the gist.](https://gist.github.com/Milly/c8a3b32f96ce603eff008906925274f4)

vimrc and test function
```vim
let $LANG = 'C'
set nocompatible

set rtp^=C:/work/vim/denops.vim
set rtp^=C:/work/vim/ddu.vim
set rtp^=C:/work/vim/ddu-ui-ff
set rtp^=C:/work/vim/ddu-kind-word
set rtp^=C:/work/vim/ddu-source-action
set rtp^=C:/work/vim/ddu-source-callbackfreeze

call ddu#custom#patch_global(#{ ui: 'ff' })

augroup my-ddu-ff
  autocmd!
  autocmd FileType ddu-ff call SetupDduFF()
augroup END

function! SetupDduFF() abort
  nnoremap <buffer><nowait> a  <Cmd>call ddu#ui#do_action('chooseAction')<CR>
  nnoremap <buffer><nowait> q  <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

function! Test() abort
  " Start source-callbackfreeze and ui-ff is shown.
  call ddu#start(#{ sources: [#{ name: 'callbackfreeze' }] })

  " Press 'a' in ui-ff and source-acition is shown.
  call timer_start(2000, {_ -> feedkeys('a')})

  " Press 'q' in ui-ff and source-acition is quit.
  " Then source-callbackfreeze shows again and refresh data.
  " But refresh process deadlocks and Vim freezes.
  call timer_start(4000, {_ -> feedkeys('q')})

  " The error is caused by source-callbackfreeze timeout.
endfunction
```

sample ddu-source
```typescript
// denops/@ddu-sources/callbackfreeze.ts

import {
  BaseSource,
  type GatherArguments,
  type OnInitArguments,
} from "https://deno.land/x/ddu_vim@v2.7.0/base/source.ts";
import { type Denops } from "https://deno.land/x/ddu_vim@v2.7.0/deps.ts";
import type { Item } from "https://deno.land/x/ddu_vim@v2.7.0/types.ts";
import * as lambda from "https://deno.land/x/denops_std@v4.1.0/lambda/mod.ts";

const TIMEOUT = 10_000; // [msec]

type Params = Record<string, never>;

export class Source extends BaseSource<Params> {
  override kind = "word";

  override params(): Params {
    return {};
  }

  override async onInit(_: OnInitArguments<Params>): Promise<void> {}

  override gather(args: GatherArguments<Params>): ReadableStream<Item[]> {
    const { denops } = args;
    return new ReadableStream({
      start: async (controller) => {
        const data = await this.#getDataFromVim(denops);
        controller.enqueue([{
          word: `Vim's data: ${data}`,
        }]);
        controller.close();
      },
    });
  }

  async #getDataFromVim(denops: Denops): Promise<unknown> {
    const data = await new Promise(
      (resolve, reject) => {
        const id = lambda.register(
          denops,
          (...args: unknown[]) => resolve(args),
          { once: true },
        );
        setTimeout(() => reject(new Error("timeout")), TIMEOUT);

        // This call is blocked if this source called from denops#request()
        denops.eval(
          "timer_start(100, {_ -> denops#notify(name, id, ['foobar'])})",
          { id, name: denops.name },
        );

      },
    );
    return data;
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Start with `vim -Nu vimrc`.
2. Do `:call Test()`.

## Upload the log messages by `:redir` and `:message` (if errored)

(Edited line breaks easier to see.)

```
Error detected while processing function ddu#ui#do_action[5]
  ..ddu#ui_action[1]
  ..ddu#_request[22]
  ..denops#request[1]
  ..denops#server#request[4]
  ..denops#_internal#server#chan#request[4]
  ..denops#_internal#rpc#vim#request[3]
  ..function ddu#ui#do_action[5]
  ..ddu#ui_action[1]
  ..ddu#_request[22]
  ..denops#request[1]
  ..denops#server#request[4]
  ..denops#_internal#server#chan#request[4]
  ..denops#_internal#rpc#vim#request:
line    3:
E605: Exception not caught:
Error: Failed to call 'uiAction' with ["default","quit",{}]:
Error: Failed to call 'call' with ["ddu#pop","default"]:
Error: Failed to call 'ddu#pop(default)':
Error: Failed to call 'pop' with ["default",{}]:
Error: timeout
    at file:///C:/work/vim/ddu-source-callbackfreeze/denops/@ddu-sources/callbackfreeze.ts:46:33
    at Object.action (ext:deno_web/02_timers.js:146:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:63:10)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async Service.dispatch (file:///C:/work/vim/denops.vim/denops/@denops-private/service.ts:117:14)
    at async dispatch (file:///C:/work/vim/denops.vim/denops/@denops-private/host/vim.ts:85:12)
    at async Session.<anonymous> (file:///C:/work/vim/denops.vim/denops/@denops-private/host/vim.ts:57:14)
function ddu#ui#do_action[5]
  ..ddu#ui_action[1]
  ..ddu#_request[22]
  ..denops#request[1]
  ..denops#server#request[4]
  ..denops#_internal#server#chan#request[4]
  ..denops#_internal#rpc#vim#re
```

**Comment by Milly** [comment]
In other words, the Vim UI hangs while `ddu#ui_action()` is processing the source updates.

**Comment by Shougo** [comment]
`ddu#ui#do_action()` executes action asynchronously.
Please update ddu.vim.

**Comment by Milly** [comment]
Thank you for fix. But I'm still having issues.
Probably because `ddu#pop()` is synchronous.

```
Error: Failed to call 'uiAction' with ["default","quit",{}]:
Error: Failed to call 'call' with ["ddu#pop","default"]:
Error: Failed to call 'ddu#pop(default)':
Error: Failed to call 'pop' with ["default",{}]:
Error: timeout
    at file:///C:/work/vim/ddu-source-callbackfreeze/denops/@ddu-sources/callbackfreeze.ts:46:33
    at Object.action (ext:deno_web/02_timers.js:146:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:63:10)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async Service.dispatch (file:///C:/work/vim/denops.vim/denops/@denops-private/service.ts:117:14)
    at async dispatch (file:///C:/work/vim/denops.vim/denops/@denops-private/host/vim.ts:85:12)
    at async Session.<anonymous> (file:///C:/work/vim/denops.vim/denops/@denops-private/host/vim.ts:57:14)
function denops#api#vim#call[2]
  ..ddu#pop[1]
  ..ddu#_request[22]
  ..denops#request[1]
  ..denops#server#request[4]
  ..denops#_internal#server#chan#request[4]
  ..denops#_internal#rpc#vim#request, line 3
    at Vim.call (file:///C:/work/vim/denops.vim/denops/@denops-private/host/vim.ts:37:13)
    at async Session.call (file:///C:/work/vim/denops.vim/denops/@denops-private/service.ts:163:14)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async DenopsImpl.call (file:///C:/work/vim/denops.vim/denops/@denops-private/impl.ts:40:12)
    at async quit (file:///C:/work/vim/ddu-ui-ff/denops/@ddu-uis/ff.ts:870:7)
    at async Ddu.uiAction (file:///C:/work/vim/ddu.vim/denops/ddu/ddu.ts:695:15)
    at async Session.uiAction (file:///C:/work/vim/ddu.vim/denops/ddu/app.ts#168.0576:248:7)
    at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:99:12)
    at async https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:108:18
    at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:104:29)
    at Session.call (https://deno.land/x/msgpack_rpc@v3.1.6/session.ts:207:13)
    at async Service.dispatch (file:///C:/work/vim/denops.vim/denops/@denops-private/service.ts:117:14)
    at async dispatch (file:///C:/work/vim/denops.vim/denops/@denops-private/host/vim.ts:85:12)
    at async Session.<anonymous> (file:///C:/work/vim/denops.vim/denops/@denops-private/host/vim.ts:57:14)
```

**Comment by Shougo** [comment]
Fixed.  Please update `ddu.vim`.

**Comment by Milly** [comment]
Works fine. Thanks!
